DO
$$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name = 'booking_status') THEN
            CREATE TABLE booking_status
            (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                booking_status_type varchar(255)                            NOT NULL,
                CONSTRAINT "bookingStatusPK" PRIMARY KEY (id)
            );
            INSERT INTO booking_status (booking_status_type)
            VALUES ('NOT_PAID'),
                   ('PAID'),
                   ('OVERDUE'),
                   ('CANCELED');
        end if;
    END
$$;



