include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test

maven_build:
  stage: build
  image: maven:3.6.0-jdk-11-slim
  cache:
    paths:
      - .m2/repository
  script:
    - echo "Compiling the code..."
    - mvn clean install
    - echo "Compile complete."
  only:
    - merge_requests