services:
 - name: docker:dind
   command: ["--tls=false"]

stages:
  - build
  - test

include:
  - template: Code-Quality.gitlab-ci.yml

variables:
 DOCKER_HOST: "tcp://docker:2375"
 DOCKER_TLS_CERTDIR: ""
 DOCKER_DRIVER: overlay2
 MAVEN_OPTS: >-
   -Dhttps.protocols=TLSv1.2
   -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
   -Dorg.slf4j.simpleLogger.showDateTime=true
   -Djava.awt.headless=true
 MAVEN_CLI_OPTS: >-
   --batch-mode
   --errors
   --fail-at-end
   --show-version

image: maven:3.6.0-jdk-11-slim

maven_build:
  stage: build
  cache:
    paths:
      - .m2/repository
  script:
    - echo "Compiling the code..."
    - 'mvn $MAVEN_CLI_OPTS clean install'
    - echo "Compile complete."
  only:
    - merge_requests