include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test

maven_build:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean install
    - echo "Compile complete."
  only:
    - merge_requests