version: '2'

services:
  app:
    image: 'airline-project:latest'
    build:
      context: ""
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/airline_db

  db:
    image: 'postgres:12.12'
    container_name: db
    environment:
      - POSTGRES_DB=airline_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root