server:
  port: 8086
  servlet:
    session:
      timeout: -1

springdoc:
  swagger-ui:
    path: swagger-ui
    enabled: true
    oauth2:
      enabled: true

app:
  feign:
    config:
      name: Project
      url: http://localhost:8080

feign:
  okhttp:
    enabled: true

spring:
  main:
    allow-bean-definition-overriding: true