UPDATE booking SET booking_status= 'PAID' where id=1;
UPDATE booking SET booking_status= 'PAID' where id=2;
UPDATE booking SET booking_status= 'PAID' where id=3;
UPDATE booking SET booking_status= 'NOT_PAID' where id=4;
UPDATE booking SET booking_status= 'PAID' where id=5;
UPDATE booking SET booking_status= 'PAID' where id=6;
UPDATE booking SET booking_status= 'PAID' where id=7;
UPDATE booking SET booking_status= 'PAID' where id=8;
UPDATE booking SET booking_status= 'NOT_PAID' where id=9;
UPDATE booking SET booking_status= 'PAID' where id=10