server:
  port: 8082
  servlet:
    session:
      timeout: -1


spring:
  application.name: frontend

app:
  feign:
    config:
      name: Project
      url: http://localhost:8080

feign:
  okhttp:
    enabled: true