server:
  port: 8082
  servlet:
    session:
      timeout: -1

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId},%X{spanId}]"
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG

app:
  feign:
    config:
      name: Project
      url: http://localhost:8080

feign:
  okhttp:
    enabled: true

spring:
  application.name: frontend
  devtools:
    restart:
      enabled: true

