server:
  port: 8084
  servlet:
    session:
      timeout: -1

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 789742733227-to2b329polor0f7l5dq3uknq35e3n44c.apps.googleusercontent.com
            client-secret: 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

  application:
    name: airlinegoogleOauth


